### ISSUE TITLE
Connecting to shard head

### ISSUE THREAD

**Issue by kenahoo-windlogics** [jeroenooms/mongolite#11]
When I connect to a `mongos` server instead of a `mongod` server, I get the following message:

```
> m <- mongo(url="mongodb://user:pass@host", db="mydb", collection="mycoll")
Mongo Message: Unexpectedly connected to sharded cluster: host
```

Is that anything to worry about?  Some way to pass different parameters to make it non-unexpected?

**Comment by jeroenooms** [comment]
@ajdavis any idea what this means?

**Comment by ajdavis** [comment]
libmongoc 1.1.x expects, wrongly, that if you connect to a mongos, that you *always* do mongos high-availability with multiple hosts in the URL. File a bug if you like, it's fixed in the 1.2 branch or will be. Fixed by @hanumantmk and @samantharitter as a general reimplementation of the mongoc_client_t to conform to my [Server Discovery And Monitoring spec](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst).

**Comment by kenahoo-windlogics** [comment]
Okay, thanks.

**Comment by jeroenooms** [comment]
I'll leave this open until we can merge in the upstream fix so that you can test it.

**Comment by jeroenooms** [comment]
@ajdavis was this fixed in 1.1.7 or not yet?

**Comment by ajdavis** [comment]
Not yet. Still awaiting the 1.2.0 release; it can't be fixed in the 1.1.x branch. 1.2.0 will be out this summer with vastly improved and standardized logic for connecting to replica sets and sharded clusters.

**Comment by jeroenooms** [comment]
Hi @kenahoo-windlogics, I have updated the development version of mongolite to `mongoc 1.2.0`. Can you give this a try?

```r
devtools::install_github("jeroenooms/mongolite")
```

**Comment by kenahoo** [comment]
Seems to make the warning go away, thanks.
