### ISSUE TITLE
Support no timeout flag for mongo cursor

### ISSUE THREAD

**Issue by vladsandulescu** [jeroenooms/mongolite#34]
For very large collections, the mongo cursor times out after 5 minutes by default. However, it's possible to pass a no-timeout flag to the 'find' command, as documented at http://api.mongodb.org/c/current/mongoc_cursor_set_max_await_time_ms.html. Would be cool for the 'find' method of your package to support this flag.

**Comment by jeroenooms** [comment]
Hmmm the documentation says:

> Only applies if the cursor is created from mongoc_collection_find with the query flags `MONGOC_QUERY_TAILABLE_CURSOR` and `MONGOC_QUERY_AWAIT_DATA`

However currently the driver [does not pass any flags](https://github.com/jeroenooms/mongolite/blob/master/src/collection.c#L164). 

So your query is actually timing out?

**Comment by vladsandulescu** [comment]
Hi,

Yes, it times out when i do a count. You could reproduce this for example
by querying a large collection without an index on it or something like
that. Afaik, there should be a way to tell Mongo not to time out. I
remember I did that from the C# driver some time ago.

Best,
Vlad

**Comment by jeroenooms** [comment]
@ajdavis is there an option in mongo-c-driver to prevent count/find from timing out? (even with `MONGOC_QUERY_NONE`)?

**Comment by ajdavis** [comment]
Pass MONGOC_QUERY_NO_CURSOR_TIMEOUT instead of MONGOC_QUERY_NONE. =)

http://api.mongodb.org/c/current/mongoc_query_flags_t.html

**Comment by ajdavis** [comment]
Oops, that says "Flags for deletion operations", but it's actually query flags.

**Comment by jeroenooms** [comment]
Great :-) Fixed @ https://github.com/jeroenooms/mongolite/commit/eb8cf3f0dfb3b6ff45edb7b39983ce52139ae4d8

**Comment by ajdavis** [comment]
Hmm, are you certain that was a good change? I didn't know you intended to disable all cursor timeouts. A cursor only times out if the client begins a query, fetches the first batch, and then fetches no more batches for *10 minutes*. If your program goes idle for 10 minutes the cursor is deleted from the server, otherwise not. A query that takes ten minutes total does *not* timeout.

The main reason for a cursor timeout is in case your client crashes while it has an open cursor. If you disable all timeouts, the server has to keep those cursors in memory forever (until mongod restarts).

I propose reverting your change, and instead offering users the *option* to explicitly disable cursor timeouts for cases where they need to do many minutes of processing per document.

**Comment by jeroenooms** [comment]
Right, I guess that makes sense. I'm trying to keep this client simple with not too many bells and whistles but maybe I am being overly lazy here.

By the way it would be really nice if libmongo would support setting config parameters (such as timeout) via environment variables, rather than requiring explicit bindings for each possible flag in all drivers. The libcurl library does something similar and it tremendously reduces complexity. But I think i've mentioned this before already :)

**Comment by jeroenooms** [comment]
Add options: https://github.com/jeroenooms/mongolite/commit/bbfbf80bd0c38fc70a803abe5304d941039ed91a

**Comment by jerome-laurent-pro** [comment]
Thank you for adding this option.

But I have a small question : is there any way to use it with the wrapper functions like `connection$aggregate()` ? The `no_timeout `argument is unused.
Currently, I don't know how to use it without forking your package. But I'm quite sure I'm missing something obvious.

**Comment by jeroenooms** [comment]
You're not missing anything obvious :-) I was working on this in the train and then reverted the default  and haven't gotten around wrapping it up yet ...

**Comment by jerome-laurent-pro** [comment]
I tried to do a fork on my own but it didn't work.
Interestingly, even with `devtools::install_github("jeroenooms/mongolite", ref = "eb8cf3f0dfb3b6ff45edb7b39983ce52139ae4d8")` (the commit with the timeouts disabled) do I still have an error.

In case it is of any help :

The command 
`aggregation_tot <- m$aggregate(json_big_aggreg)`
Produces 
` Imported 0 records. Simplifying into dataframe...`
after exactly 5 minutes.

Whereas, `/var/log/mongodb/mongod.log` show me:

`2016-05-10T09:50:21.755+0200 I NETWORK  [initandlisten] connection accepted from XXXXXXX #1 (1 connection now open)`
`2016-05-10T09:58:11.189+0200 I COMMAND  [conn1] command XXXXXXXX: aggregate { ... } protocol:op_query 469430ms`, roughly 8 minutes
`2016-05-10T09:58:11.189+0200 I NETWORK  [conn1] end connection XXXXXXX (0 connections now open)`

It seems to me that the query is correctly executed by mongoDB but `mongolite` disconnects before fetching the results.
If I do this aggregation directly in the shell, I obtain a result after 8 minutes.

I thought it was a timeout issue but maybe it isn't. Should I open another issue ?

**Comment by ajdavis** [comment]
5 minutes is the c driver sockettimeoutms. This is completely distinct from
cursor timeout in the server. To run an aggregation that takes over 5
minutes without disconnecting, increase sockettimeoutms with the connection
string:

mongodb://host/?sockettimeoutms=1200000

**Comment by jerome-laurent-pro** [comment]
Thanks for your help. It resolved my issue.

**Comment by vladsandulescu** [comment]
Thumbs up guys!

**Comment by pevzner** [comment]
Thank you guys, this thread was super helpful!
