### ISSUE TITLE
? Insert POSIXt date before 1969 -12-07 gives "Error: Invalid read of double in state 4"

### ISSUE THREAD

**Issue by leifwenn** [jeroenooms/mongolite#45]
Attempts to insert dates before 1969-12-07 give the error listed. Is this mongolite, or am I doing something wrong with my database?

s = seq(-3,3,1)_24_3600
xx = as.POSIXct("1969-12-07") + s
xx
for (i in 1:length(s)) tryCatch({db_mgl$insert(as.data.frame(xx[i]))}
                                ,error = function(e) print(paste(xx[i],' gives an error')))

db_mgl = mongolite::mongo(collection = coll,
          url = paste0("mongodb://",
                       user,":",pass,"@",
                       host[1],":",port,
                       host[2],":",port,
                       "/",database))

**Comment by jeroenooms** [comment]
hmm i think they get stored as `int64` millisec since the epoch?

**Comment by leifwenn** [comment]
Epoch starts 1970 01 01? (1960?) Is the problem with storing a negative
number?

Any suggestion for a workaround? We've been using rmongodb, and are trying
to move over to mongolite. Absent an explanation/workaround, this is pretty
much a show stopper.

I thought maybe to try exporting json and importing, as seems required for
inserting things more complicated than data frames. A data frame is causing
the problem here; just seeking a workaround.

Stored as milliseconds would seem less of a problem for early dates, as the
number would be smaller. It's dates after 1970 that have no problem.

**Comment by leifwenn** [comment]
There is no problem in your jsonlite package, if we can store epoch times. I am looking into this alternative.

**Comment by JohnGreeley** [comment]
For some reason POSIXt datetimes before the epoch are getting converted to JSON in scientific notation (whereas POSIXt datetimes after the epoch are not converted to scientific notation). This only appears when using the POSIXt = "mongo" option.

When the pre-epoch negative timestamps in scientific notation are getting passed to the mongo c library, it results in the error "Error: Invalid read of double in state 4" Changing the digits option in the asJSON.POSIXt method from digits=0 to digits=NA allows for arbitrary precision and fixes this problem.

Since digits=0 is hardcoded for asJSON.POSIXt(POSIXt = "mongo"), there is no way to fix this in client code that uses mongolite without making this change in jsonlite. I tested this change in my code and I can confirm that it now allows for insertion of pre-1970 POSIXt dates into MongoDB.

See jeroenooms/jsonlite#155 for the fix.
